name: PHP Compatibility Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring

      - name: Install Composer
        run: sudo apt-get install -y composer

      - name: Create temporary composer.json
        run: echo '{}' > composer.json

      - name: Configure Composer to allow plugins
        run: composer config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install PHPCompatibility standard
        run: |
          composer require --dev dealerdirect/phpcodesniffer-composer-installer
          composer require --dev phpcompatibility/php-compatibility

      - name: Run PHPCompatibility check
        run: vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion 8.2 . --ignore=vendor/*,tests/*,*.js,*.css
