name: PHP Compatibility Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring

    - name: Install Composer dependencies
      run: composer install

    - name: Install PHPCompatibility standard
      run: |
        composer require --dev dealerdirect/phpcodesniffer-composer-installer
        composer require --dev phpcompatibility/php-compatibility

    - name: Run PHPCompatibility check
      run: vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion 8.2 .
